import type { Metadata } from "next";
import { Montserrat, Nunito } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

const monserrat = Montserrat({
  variable: "--font-monserrat",
  display: "swap",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  weight: "400",
  display: "swap",
  subsets: ["latin"],
});

const benedict = localFont({
  src: "../Mistress Benedict Brush.ttf",
  variable: "--font-benedict",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.className} ${nunito.variable} ${benedict.variable} text-[#808080] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
